version: '3'
services:
  router:
    image: traefik:v3.1
    command:
      - "--api.dashboard=true"
      # - "--api.insecure=true"
      - "--log.level=DEBUG"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--providers.docker.network=traefik-public"
      - "--entryPoints.websecure.address=:443"
      - "--certificatesresolvers.myresolver.acme.tlschallenge=true"
      - "--certificatesresolvers.myresolver.acme.email=pablo@streameth.org"
      - "--certificatesresolvers.myresolver.acme.storage=/letsencrypt/acme.json"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.web.http.redirections.entrypoint.to=websecure"
      - "--entrypoints.web.http.redirections.entrypoint.scheme=https"
    labels:
      - "traefik.enable=true"
      # Staging route
      - "traefik.http.routers.to-staging.rule=Host(`staging.api.streameth.org`)"
      - "traefik.http.routers.to-staging.service=staging-server"
      - "traefik.http.routers.to-staging.tls=true"
      - "traefik.http.routers.to-staging.tls.certresolver=myresolver"
      # Production route
      - "traefik.http.routers.to-prod.rule=Host(`prod.api.streameth.org`)"
      - "traefik.http.routers.to-prod.service=prod-server"
      - "traefik.http.routers.to-prod.tls=true"
      - "traefik.http.routers.to-prod.tls.certresolver=myresolver"
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    networks:
      - traefik-public
      - default
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - letsencrypt:/letsencrypt
    deploy:
      placement:
        constraints:
          - node.role == manager

networks:
  default:
  traefik-public:
    external: true

volumes:
  letsencrypt:
