version: '3.8'

services:
  proxy:
    image: nginx:alpine
    container_name: proxy
    ports:
      - '80:80'
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    restart: 'unless-stopped'
    networks:
      - backend
  server:
    build:
      context: ./
      target: development-build-stage
      dockerfile: Dockerfile
    container_name: server
    ports:
      - '3400:3400'
    restart: 'unless-stopped'
    networks:
      - backend
    links:
      - mongodb
    depends_on:
      - mongodb

  mongodb:
    image: mongo:5.0.6
    restart: unless-stopped
    container_name: mongo
    ports:
      - '27017:27017'
    networks:
      - backend

networks:
  backend:
    driver: bridge

volumes:
  mongodb:
  data:
    driver: local
